spring:
  config:
    activate:
      on-profile: worker
  main:
    web-application-type: none
  temporal:
    workers-auto-discovery:
      enabled: true
      workflow-packages:
        - com.simonrowe.reviewer.workflow
      register-activity-beans: true
