package com.simonrowe.aggregation.newsletter;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

/**
 * Reads the stories out of one TLDR issue's HTML.
 *
 * <p>Every story in every TLDR edition has the same shape: an anchor wrapping a bold headline
 * that ends in a parenthesised label ({@code (5 minute read)}, {@code (GitHub Repo)},
 * {@code (Sponsor)}), followed by a span holding the summary. Section headings are {@code h1}s
 * between them. The parser keys on that shape rather than on any class name, because the class
 * names are generated by the mail builder and change between issues.
 *
 * <p>The label is what makes this safe against everything else in the message. Confirmation
 * mails, referral links, the "advertise with us" footer and the unsubscribe link carry no
 * labelled bold headline, so they produce no story and are never followed.
 */
final class TldrIssueParser {

  private static final String SPONSOR = "sponsor";

  /** A headline is short; a longer "label" is prose that happens to end in a bracket. */
  private static final int MAX_LABEL_LENGTH = 40;

  private TldrIssueParser() {
  }

  /**
   * Parses an issue.
   *
   * @param html the message's {@code text/html} part
   * @return its stories in reading order, sponsored slots excluded
   */
  static List<NewsletterStory> parse(final String html) {
    if (html == null || html.isBlank()) {
      return List.of();
    }
    final Document doc = Jsoup.parse(html);
    final List<NewsletterStory> stories = new ArrayList<>();
    String section = null;
    // One selector group, so the h1s and anchors come back in document order and each story
    // picks up the heading above it.
    for (Element element : doc.select("h1, a[href]")) {
      if ("h1".equals(element.tagName())) {
        section = element.text().trim();
        continue;
      }
      story(element, section).ifPresent(stories::add);
    }
    return List.copyOf(stories);
  }

  private static Optional<NewsletterStory> story(final Element anchor, final String section) {
    final Element strong = anchor.selectFirst("strong");
    if (strong == null) {
      return Optional.empty();
    }
    final String headline = strong.text().trim();
    final int open = headline.lastIndexOf('(');
    if (open <= 0 || !headline.endsWith(")")) {
      return Optional.empty();
    }
    final String label = headline.substring(open + 1, headline.length() - 1).trim();
    if (label.isEmpty() || label.length() > MAX_LABEL_LENGTH
        || label.toLowerCase(Locale.ROOT).contains(SPONSOR)) {
      return Optional.empty();
    }
    final String title = headline.substring(0, open).trim();
    if (title.isEmpty()) {
      return Optional.empty();
    }
    return NewsletterLinks.unwrap(anchor.attr("href"))
        .map(url -> new NewsletterStory(title, url, summaryAfter(anchor), section, label));
  }

  /** The first span after the headline anchor, which is where every issue puts the summary. */
  private static String summaryAfter(final Element anchor) {
    Element sibling = anchor.nextElementSibling();
    while (sibling != null) {
      if ("span".equals(sibling.tagName())) {
        return sibling.text().trim();
      }
      sibling = sibling.nextElementSibling();
    }
    return "";
  }
}
