#!/usr/bin/env bash
#
# Guards the chain that lets Dependency-Track see OS packages at all.
#
# Until 2026-08-31 no enabled vulnerability source could match `pkg:apk/*` or
# `pkg:deb/*`, so `simonrowe-dev/frontend-image` reported Risk Score 0 while
# carrying 20 fixable Alpine findings (2 HIGH) on openssl, and `backend-image`
# reported 1 of ~242 real Ubuntu findings. Nothing logged an error: a container
# project's 0 meant "unscannable", and reads identically to "clean".
#
# Two links carry that fix, and BOTH fail silently - the symptom of breaking
# either is 0 findings, never a red build or a log line. Hence this file.
#
#   1. The image SBOMs must be generated by TRIVY. Dependency-Track resolves an
#      OS package's source package from the `aquasecurity:trivy:SrcName`
#      component property and falls back to the purl's *binary* name when it is
#      absent (TrivyVulnAnalyzer.processOsPackage). Only trivy emits it; syft
#      records the same fact as an `upstream=` purl qualifier, which
#      Dependency-Track never reads. Measured against one trivy server, same
#      image, same 71 apk packages: trivy SBOM 20 findings, syft SBOM 0.
#
#   2. `trivy-server` must be in FACTORY_DEPLOY_RECREATABLE. That list is an
#      allowlist, and a compose change to a service outside it makes sync-config
#      decline as `held-back` - which leaves the deploy directory frozen and is
#      self-perpetuating, the wedge that stranded #130 through #136.
#
# Deliberately NOT asserted here: that the Trivy analyzer is enabled inside
# Dependency-Track. That is runtime config in Postgres (read via
# getRuntimeConfig), settable by no environment variable and reconcilable by no
# deploy, so no file in this repo can be the source of truth for it. It is a
# one-time manual step; docs/runbooks/dependency-track.md owns it.
#
# A shell test rather than a Java one because the subjects are a workflow file
# and a compose file, owned by neither Gradle module - the same reasoning as
# test-frontend-nginx-shipping.sh, which this follows closely.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

COMPOSE_FILE="$PROJECT_DIR/docker-compose.prod.yml"
WORKFLOW="$PROJECT_DIR/.github/workflows/publish.yml"

failures=0
checks=0

check() {
  local description="$1" condition="$2"
  checks=$((checks + 1))
  if eval "$condition"; then
    echo "    ok: $description"
  else
    failures=$((failures + 1))
    echo "    FAIL: $description"
  fi
}

# Comment lines are dropped for the same reason DeployerLinearCredentialTest and
# test-frontend-nginx-shipping.sh drop them: the comments here explain what must
# NOT come back and therefore name it, so a scan over raw lines would fail on its
# own rationale and teach the next person to delete the explanation.
uncommented() {
  grep -vE '^[[:space:]]*#' "$1"
}

# ---------------------------------------------------------------------------
echo "  the subjects exist"
# ---------------------------------------------------------------------------
# Without these, every assertion below passes by reading nothing.
check "docker-compose.prod.yml exists" "[[ -f '$COMPOSE_FILE' ]]"
check ".github/workflows/publish.yml exists" "[[ -f '$WORKFLOW' ]]"

WORKFLOW_BODY="$(uncommented "$WORKFLOW")"
COMPOSE_BODY="$(uncommented "$COMPOSE_FILE")"
check "publish.yml still declares the SBOM job this guards" \
  "grep -q 'Publish SBOMs to Dependency-Track' <<<\"\$WORKFLOW_BODY\""

# ---------------------------------------------------------------------------
echo "  the three image SBOMs are generated by trivy"
# ---------------------------------------------------------------------------
for svc in backend frontend software-factory; do
  check "publish.yml writes ${svc}-image-bom.json" \
    "grep -qF 'output: ${svc}-image-bom.json' <<<\"\$WORKFLOW_BODY\""
done

trivy_steps="$(grep -c 'uses: aquasecurity/trivy-action@' <<<"$WORKFLOW_BODY")"
check "publish.yml uses aquasecurity/trivy-action for all three images (found $trivy_steps)" \
  "[[ '$trivy_steps' -eq 3 ]]"

# The tag really is `v`-prefixed (`v0.36.0`); the bare `0.36.0` form other Aqua
# actions use does not exist on this repo and fails the job with "unable to
# resolve action".
check "the trivy-action reference is pinned to a tag that exists (v-prefixed)" \
  "grep -qE 'uses: aquasecurity/trivy-action@v[0-9]+\.[0-9]+\.[0-9]+' <<<\"\$WORKFLOW_BODY\""

check "each trivy step requests CycloneDX output" \
  "[[ \$(grep -c 'format: cyclonedx' <<<\"\$WORKFLOW_BODY\") -eq 3 ]]"

# The negative assertion this file exists for. Reverting to syft turns OS
# coverage off and reports 0 findings rather than failing.
check "no image SBOM is generated by anchore/sbom-action (syft)" \
  "! grep -q 'anchore/sbom-action' <<<\"\$WORKFLOW_BODY\""

# An empty or {} BOM uploads successfully and also reads as "clean" on the
# Projects page, so the generator failing must not look like a clean scan.
check "publish.yml asserts the generated image SBOMs are not empty" \
  "grep -q 'Assert the image SBOMs are not empty' <<<\"\$WORKFLOW_BODY\""

# ---------------------------------------------------------------------------
echo "  the trivy server is declared and deployable"
# ---------------------------------------------------------------------------
check "the compose file declares a \`trivy-server\` service" \
  "grep -qE '^  trivy-server:' <<<\"\$COMPOSE_BODY\""
check "trivy-server pins an explicit image tag rather than floating on latest" \
  "grep -qE '^    image: aquasec/trivy:[0-9]+\.[0-9]+\.[0-9]+$' <<<\"\$COMPOSE_BODY\""
check "the trivy-cache volume is declared, so the 1.27GiB DB survives recreation" \
  "grep -qE '^  trivy-cache:' <<<\"\$COMPOSE_BODY\""

# Without this the merge that ADDS trivy-server is itself held back, and a
# held-back checkout is self-perpetuating.
check "trivy-server is in FACTORY_DEPLOY_RECREATABLE" \
  "grep 'FACTORY_DEPLOY_RECREATABLE:' <<<\"\$COMPOSE_BODY\" | grep -q 'trivy-server'"

# `:?` here would make the WHOLE compose file fail to interpolate when unset,
# which both wedges sync-config and breaks monitor-prod.sh's minutely `up -d`,
# taking the self-healing watchdog down with it.
check "the trivy token uses a \`:-\` default, never a \`:?\` required variable" \
  "grep -q 'TRIVY_SERVER_TOKEN:-' <<<\"\$COMPOSE_BODY\""
check "no \`:?\` form of TRIVY_SERVER_TOKEN is present" \
  "! grep -q 'TRIVY_SERVER_TOKEN:?' <<<\"\$COMPOSE_BODY\""

# The published port would put a scanner on the host's network for no reason;
# nothing outside the compose network needs to reach it.
TRIVY_BLOCK="$(awk '
  $0 == "  trivy-server:" { inside = 1; next }
  inside && /^  [a-zA-Z0-9_-]+:[[:space:]]*$/ { exit }
  inside && $0 ~ /^[[:space:]]*#/ { next }
  inside { print }
' "$COMPOSE_FILE")"
check "the extracted block is really trivy-server's" \
  "grep -q 'aquasec/trivy' <<<\"\$TRIVY_BLOCK\""
check "trivy-server publishes no host port" \
  "! grep -qE '^[[:space:]]*ports:' <<<\"\$TRIVY_BLOCK\""
check "trivy-server has a healthcheck" \
  "grep -qE '^[[:space:]]*healthcheck:' <<<\"\$TRIVY_BLOCK\""
# /healthz answers only after the DB is loaded, so it is a real readiness probe -
# but a cold start must download 1.27GiB, which needs a start_period well past
# the retries x interval budget.
check "trivy-server's healthcheck probes /healthz" \
  "grep -q '/healthz' <<<\"\$TRIVY_BLOCK\""
check "trivy-server declares a start_period for the cold DB download" \
  "grep -qE '^[[:space:]]*start_period:' <<<\"\$TRIVY_BLOCK\""

# ---------------------------------------------------------------------------
echo
if [[ "$failures" -gt 0 ]]; then
  echo "  $failures of $checks checks failed"
  exit 1
fi
echo "  all $checks checks passed"
